[package]
name = "atom-feed"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
quick-xml = { version = "0.37.1", features = ["serde", "serialize"] }
serde = { version = "1.0.204", features = ["derive"] }
